### ISSUE TITLE
Dock not showing on 11.3.1

### ISSUE THREAD

**Issue by peterflaherty** [pock/dock-widget#5]
Everything is showing up **except the dock.** no image in the "customize Touch Bar" section of the dock, so I cant drag it onto the Touch Bar. . Ive tried re-installing the widget, but no luck.

**Comment by smdavisjr** [comment]
Running 11.2.3 and experiencing the same issue

**Comment by vinsonma** [comment]
Running 11.2.3 and experiencing the same issue

**Comment by easp** [comment]
Same issue.
Running MacOS 11.5.2 , Pock 0.8.1-5 and Dock widget 1.1-8.
